# Window settings

[window]

opacity = 0.7

# Font config, because Intel One Mono is GOAT

[font]

normal = { family = "Intel One Mono", style = "Regular" }

[colors]

[colors.primary]

background = "#74b0bc"
foreground = "#eaf1f2"
